version: '3.8'

services:
  binancebot:
    image: lucianoromao/binance_bot:1.1
    container_name: BinanceBot
    environment:
      api_key_binance: 'your_token'
      api_secret_biance: 'your_token'
      telegram_bot_token: 'your_token'
      telegram_chat_id: 'your_token'
      mongo_uri: your_string_uri
      mongo_collection: your_collection
 
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

  mongodb:
    image: mongo:latest
    container_name: mmongoDB
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - /c/Users/Luciano Romão/projetos/volumes/mongodb:/data/db

  mongo-express:
    image: mongo-express:latest
    container_name: mongoDBexpress
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mongodb
    depends_on:
      - mongodb